dotenv-linter/dotenv-linter

- .github/workflows/audit.yml
> Add GitHub Action for security audit

- .github/workflows/rust.yml
- src/lib.rs
> Add GitHub Action

- README.md
- src/checks.rs
- src/checks/leading_space.rs
- src/lib.rs
- src/main.rs
What should be done:
Close #13
> Prepare a template for easy adding new checks

- src/lib.rs
> Add `Display` trait for `LineEntry`

- README.md
- src/checks.rs
- src/checks/key_without_value.rs
> Add key without value check

- src/checks.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_space.rs
> Replace field warning with template for all check structs

- README.md
- src/checks.rs
- src/checks/lowercase_key.rs
Closes https://github.com/mgrachev/dotenv-linter/issues/6
> Lowercase checker

- Cargo.toml
- src/main.rs
> Add support for command line arguments

- src/lib.rs
> Skip commented lines with leading spaces

- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/spaces_around_equal.rs
> #9 Add check for spaces around equal sign

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- README.md
- src/lib.rs
- src/main.rs
> Add ability to include files to check

- CHANGELOG.md
- README.md
- src/lib.rs
- src/main.rs
> Add `exclude|e` argument to handle exlcuding files

- README.md
- src/checks.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_space.rs
- src/checks/lowercase_key.rs
- src/checks/spaces_around_equal.rs
- src/lib.rs
> Add mutability support for checks

- CHANGELOG.md
- src/lib.rs
I added a verification on the amount of warnings found and exit with 1 as error code when the number or warnings is more than 0.
Should solve #47 .
> Exit code on warnings

- .github/workflows/release.yml
- CHANGELOG.md
- Dockerfile
- src/lib.rs
> Publish Docker image to Docker Hub

- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/duplicated_keys.rs
- src/lib.rs
> Add `duplicated_keys` check

- src/checks.rs
- src/checks/duplicated_keys.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_space.rs
- src/checks/lowercase_key.rs
- src/checks/spaces_around_equal.rs
- src/common.rs
- src/lib.rs
- src/main.rs
* Exit in only one place;
* Add the ability to test funtions in `lib.rs`.
> Fix some issues

- .github/workflows/ci.yml
- README.md
> Push test coverage to codecov

- src/checks.rs
- src/common.rs
> Add tests for modules

- .codecov.yml
- .editorconfig
- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/duplicated_keys.rs
- src/checks/unordered_keys.rs
> Add check: Unordered keys

- README.md
- RELEASING.md
> Add `RELEASING.md`

- .dockerignore
- .github/workflows/release.yml
- CHANGELOG.md
- Dockerfile
Hi mate !
I looked at how you build docker image and realized that I need to help, I updated actions and now everything happens inside Dockerfile. 
Image size has decreased
old : Total Image size: 9.2 MB 
new: Total Image size: 3.4 MB
I will be glad to have any comments :)
> refactor docker build and docker release

- CHANGELOG.md
- src/checks.rs
- src/common.rs
* LineEntry.line_is_empty_or_comment method added
> LineEntry.line_is_empty_or_comment

- CHANGELOG.md
- src/lib.rs
* Fixed --path CLI parameter handling not canonizing filepaths
> Fix --path CLI parameter

- CHANGELOG.md
- src/main.rs
- tests/cli_test.rs
> Exit with 0 when there are no warnings

- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/duplicated_key.rs
> Rename check DuplicatedKeys to DuplicatedKey

- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/space_character.rs
> Renamed spaces_around_equal to space_character.

- CHANGELOG.md
- tests/cli_test.rs
Fixes #127
Once this pull request is merged, I will open an additional pull request with a refactor of the code in [cli_test.rs](https://github.com/mgrachev/dotenv-linter/blob/master/tests/cli_test.rs); as there is now excessive code repeition in the tests.
> Add test coverage for --exclude argument

- .github/actions-rs/grcov.yml
- .github/workflows/ci.yml
- CHANGELOG.md
This PR fixes #128. Replaced kcov with grcov. Not quite sure if this will work though!
> Add grcov to Github Actions

- CHANGELOG.md
- src/checks/incorrect_delimiter.rs
> Add IncorrectDelimiter check name to the message

- CHANGELOG.md
- src/checks/lowercase_key.rs
- tests/cli_basic.rs
Added check name for lowercase checker
Resolve: #124
> #124 Add check name for lowercase checker

- CHANGELOG.md
- src/checks.rs
- src/checks/key_without_value.rs
- tests/cli_basic.rs
Hello this fixes #120 and #122 , i was initially assigned to fix #122 but i accidentally fixed #120 , pardon me. I have defined a new trait message that can be implemented in every error check.
> changed tests and errors

- CHANGELOG.md
- src/checks.rs
- src/checks/unordered_key.rs
* Renamed UnorderedKeys check to singular UnorderedKey
> Rename UnorderedKeys check to singular

- CHANGELOG.md
- src/checks/leading_character.rs
- tests/cli_exclude.rs
- tests/cli_specific.rs
- [ x] This PR has been added to [CHANGELOG.md](https://github.com/mgrachev/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);
- [ x] Tests for the changes have been added (for bug fixes / features);
> LeadingCharacter: Show check name in message #123

- CHANGELOG.md
- README.md
- src/checks/space_character.rs
- tests/cli_specific.rs
* Added check name to SpaceCharacter check output message
> Add check name to SpaceCharacter check output message

- CHANGELOG.md
- Dockerfile
> Fix docker image

- CHANGELOG.md
- README.md
- src/checks.rs
- src/checks/quote_character.rs
- src/common.rs
Added a new checker for quote characters. Includes tests for values with single and double quotes, and correct case.
> Add detection for quote characters in values

- CHANGELOG.md
- src/checks/key_without_value.rs
> KeyWithoutValueChecker: Replace String with &'a str

- CHANGELOG.md
- src/checks/duplicated_key.rs
> Resolves replace `String` with `&'a str`

- CHANGELOG.md
- src/checks/extra_blank_line.rs
> Fixes #186

- CHANGELOG.md
- src/checks/lowercase_key.rs
> LowercaseKeyChecker: Replace String with &'a str

- CHANGELOG.md
- src/checks/space_character.rs
> SpaceCharacterChecker: Replace String with &'a str

- CHANGELOG.md
- src/checks/unordered_key.rs
> UnorderedKeyChecker: Replace String with &'a str

- CHANGELOG.md
- src/checks/quote_character.rs
> QuoteCharacterChecker: Replace &'static str with &'a str

- CHANGELOG.md
- src/lib.rs
> Enable checks for outside current directory (#179)

- .github/workflows/ci.yml
- CHANGELOG.md
> Add build and test steps running on Windows

- CHANGELOG.md
- src/checks/duplicated_key.rs
- src/checks/quote_character.rs
I found some minor typos in the tests and made corrections
> Fix total_lines in some tests

- CHANGELOG.md
- src/fixes.rs
- src/fixes/space_character.rs
- tests/fixes/mod.rs
- tests/fixes/space_character.rs
> Add fixer: SpaceCharacterFixer (#250)

- CHANGELOG.md
- README.md
- docs/checks/quote_character.md
- src/checks/quote_character.rs
- src/fixes.rs
- src/fixes/quote_character.rs
- tests/fixes/mod.rs
- tests/fixes/quote_character.rs
- tests/flags/quiet.rs
> Implement trait `Fix` for warnings issued by `QuoteCharacterChecker`.

- CHANGELOG.md
- src/fixes.rs
- src/fixes/duplicated_key.rs
- tests/fixes/duplicated_key.rs
- tests/fixes/mod.rs
> solve #243: add DuplicatedKeyFixer

- CHANGELOG.md
- src/checks/unordered_key.rs
> Simplify UnorderedKeyChecker

- CHANGELOG.md
- src/checks.rs
- src/checks/duplicated_key.rs
- src/checks/ending_blank_line.rs
- src/checks/extra_blank_line.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_character.rs
- src/checks/lowercase_key.rs
- src/checks/quote_character.rs
- src/checks/space_character.rs
- src/checks/trailing_whitespace.rs
- src/checks/unordered_key.rs
- src/common.rs
- src/common/line_entry.rs
- src/common/warning.rs
- src/fixes.rs
- src/fixes/duplicated_key.rs
- src/fixes/ending_blank_line.rs
- src/fixes/extra_blank_line.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/key_without_value.rs
- src/fixes/leading_character.rs
- src/fixes/lowercase_key.rs
- src/fixes/quote_character.rs
- src/fixes/space_character.rs
- src/fixes/trailing_whitespace.rs
- src/fs_utils.rs
> Move logic for creating LineEntry for tests to common module

- CHANGELOG.md
- src/common.rs
- src/common/line_entry.rs
- src/fixes.rs
- src/fixes/duplicated_key.rs
- src/fixes/ending_blank_line.rs
- src/fixes/extra_blank_line.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/key_without_value.rs
- src/fixes/leading_character.rs
- src/fixes/lowercase_key.rs
- src/fixes/quote_character.rs
- src/fixes/space_character.rs
- src/fixes/trailing_whitespace.rs
- src/fs_utils.rs
- src/lib.rs
- tests/fixes/extra_blank_line.rs
> Fix a bug with ExtraBlankLineFixer and control comments

- CHANGELOG.md
- src/fixes.rs
- src/fixes/unordered_key.rs
- tests/common/mod.rs
- tests/fixes/mod.rs
- tests/fixes/unordered_key.rs
PR for https://github.com/dotenv-linter/dotenv-linter/issues/252.
> UnorderedKey fix

- CHANGELOG.md
- src/fixes.rs
- src/fixes/duplicated_key.rs
- src/fixes/unordered_key.rs
- src/lib.rs
- tests/common/mod.rs
- tests/fixes/key_without_value.rs
- tests/fixes/leading_character.rs
- tests/fixes/lowercase_key.rs
- tests/fixes/mod.rs
This PR fixes the issue #285.
There is a little duplication, but I think that is OK for now.
As far as I can see, the autofix feature is finally completed.
> Finishing autofix

- CHANGELOG.md
- README.md
- docs/quick_start.md
- src/common/warning.rs
- src/fixes.rs
- src/fixes/duplicated_key.rs
- src/fixes/ending_blank_line.rs
- src/fixes/extra_blank_line.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/key_without_value.rs
- src/fixes/lowercase_key.rs
- src/fixes/quote_character.rs
- src/fixes/trailing_whitespace.rs
- src/fixes/unordered_key.rs
- src/main.rs
- tests/common/output.rs
- tests/flags/quiet.rs
@evgeniy-r Please take a look 👀
> Remove code related to Fixed/Unfixed

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
> Add CARGO_TERM_COLOR env variable to the actions

- CHANGELOG.md
- README.md
- docs/install.md
> Add command to install latest version via Homebrew

- CHANGELOG.md
- src/main.rs
> Update args help

- .github/workflows/misspell.yml
- CHANGELOG.md
> Add misspell action

- .github/workflows/misspell.yml
> Use US locale for reviewdog/action-misspell

- CHANGELOG.md
- src/common/line_entry.rs
adds additional test for **get_value** method which is in **Line_entry.rs**
Closes #292 
Please keep this checklist in & ensure you have done the following:
> Adds additional test for LineEntry.get_value

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
We are ready to release [v2.2.0](https://github.com/dotenv-linter/dotenv-linter/issues/238) on Monday 🎉
Thanks to everyone who helped and took part in the preparation of this release ❤️
Close #238
> Release v2.2.0

- .github/workflows/ci.yml
- CHANGELOG.md
- src/main.rs
This PR is intended to add an additional step to the CI action, as a means of detecting docker build errors prior to PR completion.
> Added docker build to CI

- .github/workflows/yamllint.yml
- CHANGELOG.md
> Feature/add action-yamllint

- CHANGELOG.md
- src/lib.rs
- tests/args/specific_path.rs
- tests/flags/recursive.rs
@mgrachev 
Fixed the issue
Updated tests accordingly
Fixes #325
> #325 Linter rechecks files if they were listed more than once

- .gitattributes
- CHANGELOG.md
> Add .gitattributes to improve git diff (#329)

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/linters.yml
- CHANGELOG.md
> Add commitlint

- CHANGELOG.md
- src/checks.rs
- src/checks/duplicated_key.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/unordered_key.rs
- src/common/line_entry.rs
- src/fixes/duplicated_key.rs
- tests/checks/key_without_value.rs
- tests/checks/mod.rs
This fixes the problems described in #345.
I had to change some tests to make them pass again. Since this is my first commit, I am not quite sure if every change I made is acceptable so this will need some review.
Also I'm not sure if this fix requires any updates on the documentation repo.
> fix(#345): Find all problems

- CHANGELOG.md
- src/checks/quote_character.rs
This PR fixes the issue in #343.
> fix(#343): Add check for whitespace

- CHANGELOG.md
- README.md
> perf: add benchmark

- README.md
Thanks to @vbrandl for helping to improve performance https://github.com/dotenv-linter/dotenv-linter/pull/350 🚀
> perf: update benchmark

- README.md
> docs: add new articles

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- deny.toml
> build: release v3.0.0

- CHANGELOG.md
- README.md
For #362
Is the CHANGELOG.md change necessary?
> added .env explaination

- README.md
Description of changes:
- "more shorter" is bad English so just "shorter".
- `shell script` is unnecessary, so just `shell` for code block (BTW, `sh` also works).
- Added spacing for readability.
- Neat table formatting thanks to a VS Code markdown extension :)
- Made `/CONTRIBUTING.md` with a forward slash for consistency with other parts of the doc.
> docs: Update formatting and wording of README.md

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Dockerfile
- benches/check.rs
- benches/fixtures/simple.env
- src/cli.rs
- src/common/file_entry.rs
- src/fs_utils.rs
- src/lib.rs
- src/main.rs
> perf: add benchmark for check function

- .github/workflows/benchmark.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> perf: add benchmark action

- CHANGELOG.md
- tests/common/test_dir.rs
- tests/output/check.rs
- tests/output/fix.rs
> Replace String on Into<String> for all TestDir methods (#387)

- .github/workflows/benchmark.yml
- .gitignore
- CHANGELOG.md
- Cargo.toml
- benches/check.rs
- benches/compare.rs
- benches/fixtures/compare.env
Add benchmark for compare function.
> perf: add benchmark for compare function

- CHANGELOG.md
- src/common/output/fix.rs
- src/lib.rs
- tests/output/fix.rs
> Print message if there are no input files for fix subcommand (#385)

- .github/workflows/linters.yml
- CHANGELOG.md
Add hadolint to lints workflows for check Dockerfile. Issue (#380)
> ci: add hadolint action to workflows/lints.yml (#380)

- src/common/file_entry.rs
- src/fixes/extra_blank_line.rs
- src/fixes/unordered_key.rs
- src/fs_utils.rs
- src/lib.rs
- tests/common/output.rs
- tests/common/test_dir.rs
- tests/compare/compare.rs
- tests/options/exclude.rs
- tests/output/check.rs
- tests/output/fix.rs
Closes https://github.com/dotenv-linter/dotenv-linter/issues/402.
> Make clippy happy

- CHANGELOG.md
- src/common/output/compare.rs
- src/lib.rs
- tests/output/compare.rs
- tests/output/mod.rs
> Print a message "Nothing to compare" (#398)

- CHANGELOG.md
- src/fixes.rs
- src/fixes/duplicated_key.rs
- src/fixes/unordered_key.rs
Refactored the fixer according to the suggestion in #411, successfully ran tests and linter on the project
> refactor: hard-coded mandatory fixer (#411)

- CHANGELOG.md
- src/fixes.rs
- src/fixes/substitution_key.rs
- tests/fixes/mod.rs
- tests/fixes/substitution_key.rs
> feat: add substitution key fixer

- .github/workflows/release.yml
This should fix the issue.
Should we retrigger that pipeline?
closes #430
> ci: use correct archlinux image

- CHANGELOG.md
- src/checks/duplicated_key.rs
- src/checks/ending_blank_line.rs
- src/checks/extra_blank_line.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_character.rs
- src/checks/lowercase_key.rs
- src/checks/quote_character.rs
- src/checks/space_character.rs
- src/checks/substitution_key.rs
- src/checks/trailing_whitespace.rs
- src/checks/unordered_key.rs
- src/fixes/duplicated_key.rs
- src/fixes/ending_blank_line.rs
- src/fixes/extra_blank_line.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/key_without_value.rs
- src/fixes/leading_character.rs
- src/fixes/lowercase_key.rs
- src/fixes/quote_character.rs
- src/fixes/space_character.rs
- src/fixes/substitution_key.rs
- src/fixes/trailing_whitespace.rs
- src/fixes/unordered_key.rs
> refactor: get rid of name field in checks and fixes

- CHANGELOG.md
- src/lib.rs
> using flatten instead of filter with inwrap

- CHANGELOG.md
- src/checks/duplicated_key.rs
- src/checks/ending_blank_line.rs
- src/checks/incorrect_delimiter.rs
- src/checks/key_without_value.rs
- src/checks/leading_character.rs
- src/checks/lowercase_key.rs
- src/checks/substitution_key.rs
- src/checks/unordered_key.rs
- src/common/line_entry.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/leading_character.rs
- src/fixes/substitution_key.rs
- src/lib.rs
- src/main.rs
> chore: fix clippy warnings

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Release v3.1.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
Fix build for aarch64 (linux, macos)
> fix(release): build for aarch64

- CHANGELOG.md
- install.sh
- src/common/comment.rs
> fix: display a message on installation error

- CHANGELOG.md
- src/fixes/duplicated_key.rs
- src/fixes/ending_blank_line.rs
- src/fixes/extra_blank_line.rs
- src/fixes/incorrect_delimiter.rs
- src/fixes/key_without_value.rs
- src/fixes/leading_character.rs
- src/fixes/lowercase_key.rs
- src/fixes/quote_character.rs
- src/fixes/space_character.rs
- src/fixes/substitution_key.rs
- src/fixes/trailing_whitespace.rs
- src/fixes/unordered_key.rs
> Fix clippy warnings

- CHANGELOG.md
- src/common.rs
- src/common/quote_type.rs
- src/lib.rs
- tests/fixes/fixtures/complicated.env
- tests/fixes/fixtures/complicated.env.golden
- tests/fixes/fixtures/correct.env
- tests/fixes/fixtures/correct.env.golden
- tests/output/check.rs
Continuing to #450
Closes #442
It seems that we should update documentation. But tech-functionality is ready 🙂
> feat: add support for double quoted multi-line values

- CHANGELOG.md
- Dockerfile
> Update docker build

- CHANGELOG.md
- deny.toml
> Update cargo-deny config

- CHANGELOG.md
- src/common/line_entry.rs
- src/common/quote_type.rs
- tests/output/check.rs
It pretty simple bug. I've added test.
Closes #461
> fix(#461): fail with one quote-char in line

- README.md
> docs: add link to vote

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/lib.rs
> chore: update dependency `update-informer`

- README.md
> docs: remove link to vote

- .github/dependabot.yml
- CHANGELOG.md
> chore: add dependabot

- CHANGELOG.md
- src/fixes/quote_character.rs
- src/fixes/substitution_key.rs
- src/lib.rs
- tests/output/compare.rs
> fix: clippy warnings

- CHANGELOG.md
- deny.toml
> chore: update `cargo-deny` config

- .github/workflows/stale.yml
- CHANGELOG.md
> chore: add `stale` action

- .github/workflows/benchmark.yml
- CHANGELOG.md
> chore: update `criterion-compare` action

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/lib.rs
- src/main.rs
- tests/flags/backup.rs
> chore(deps): update `clap`

- CHANGELOG.md
- src/cli.rs
> refactor: move CLI commands to separate functions

- CHANGELOG.md
- Cargo.lock
- rust-toolchain.toml
- src/checks/duplicated_key.rs
- src/cli.rs
- src/common/comment.rs
- src/common/file_entry.rs
- src/common/output/check.rs
- src/common/output/fix.rs
- src/common/warning.rs
- src/fixes/duplicated_key.rs
- src/fs_utils.rs
- src/lib.rs
- tests/flags/mod.rs
- tests/flags/version.rs
> test: add tests to verify cli application

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/audit.yml
- .github/workflows/benchmark.yml
- .github/workflows/cargo-deny.yml
- .github/workflows/ci.yml
- .github/workflows/linters.yml
- .github/workflows/release.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Cargo.toml
- README.md
- RELEASING.md
- deny.toml
- dprint.json
- rust-toolchain.toml
> ci: add `dprint` and `lychee` actions + ci optimization

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.toml
- src/lib.rs
> ci: add job to check release builds

- .github/workflows/release.yml
- CHANGELOG.md
> ci: fix release builds

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
- Cargo.toml
- cliff.toml
- release.sh
> chore: generate a changelog and update release process

- Cargo.lock
- Cargo.toml
> chore: bump criterion from 0.3.6 to 0.4.0

- .github/workflows/ci.yml
- .github/workflows/release.yml
> ci: temporarily disable docker arm64 build

- .github/workflows/ci.yml
- install.sh
Resolves #539
Add check in install.sh to validate that the tag argument matches semver
> Check that tag is valid semver in install.sh

- src/checks.rs
- src/fixes.rs
> chore(ci): use `Box::<T>::default()` instead of `Box::new(T::default())`

- .cargo/config.toml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
Closes #572
It's quite common issue and there are a lot of issues around GH regarding this (e.g: https://github.com/docker/build-push-action/issues/621, https://github.com/rust-lang/cargo/issues/10583)
I guess it should help in our case as well
> fix(572): arm docker build

- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- cliff.toml
> Release v3.3.0

- .github/workflows/release.yml
- CHANGELOG.md
- cliff.toml
- release.sh
> chore: get rid of `orhun/git-cliff-action`

- .github/workflows/ci.yml
- .github/workflows/linters.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- benches/check.rs
- benches/compare.rs
- benches/fix.rs
- dprint.json
- install.sh
- src/cli.rs
- src/lib.rs
- src/main.rs
- tests/flags/version.rs
> chore(deps): bump `clap` from 3.1.10 to 4.0.32

- src/cli.rs
- src/lib.rs
> refactor(cli): don't display option `--not-check-updates` if it's disabled

- dotenv-linter/Cargo.toml
- dotenv-linter/src/cli/mod.rs
> feat: lint skipping env vars logic with clap env function

- dotenv-linter/src/cli/mod.rs
- dotenv-linter/tests/common/test_dir.rs
- dotenv-linter/tests/flags/check_updates.rs
Closes #593
This is my very first Rust PR, any feedback and pointers are very much appreciated!
> feat: Allow setting not_check_updates flag via env var

- .github/workflows/linters.yml
> ci: check PR name instead of commits

- Cargo.lock
- deny.toml
- dotenv-linter/Cargo.toml
> chore: bump `colored` and `criterion`

- Dockerfile
> fix(756): docker image for `linux/arm64`

- Cargo.lock
- dotenv-linter/benches/check.rs
- dotenv-linter/benches/compare.rs
- dotenv-linter/benches/fix.rs
- dotenv-linter/src/checks/schema_violation.rs
- dotenv-linter/src/cli/options.rs
> ci: fix benchmarks

- Cargo.toml
- dotenv-analyzer/src/check/ending_blank_line.rs
- dotenv-analyzer/src/check/incorrect_delimiter.rs
- dotenv-analyzer/src/check/mod.rs
- dotenv-analyzer/src/check/space_character.rs
- dotenv-analyzer/src/check/substitution_key.rs
- dotenv-analyzer/src/check/unordered_key.rs
- dotenv-analyzer/src/fix/duplicated_key.rs
- dotenv-analyzer/src/fix/ending_blank_line.rs
- dotenv-analyzer/src/fix/incorrect_delimiter.rs
- dotenv-analyzer/src/fix/leading_character.rs
- dotenv-analyzer/src/fix/substitution_key.rs
- dotenv-analyzer/src/fix/unordered_key.rs
- dotenv-finder/src/file.rs
- dotenv-linter/benches/check.rs
- dotenv-linter/benches/compare.rs
- dotenv-linter/benches/fix.rs
- dotenv-linter/src/cli.rs
- dotenv-linter/src/fs_utils.rs
- dotenv-linter/src/lib.rs
- dotenv-linter/src/main.rs
- dotenv-linter/tests/checks/schema.rs
- dotenv-linter/tests/common/test_dir.rs
> chore: update edition
