dotenv-linter/dotenv-linter

README.md
src/checks.rs
src/checks/incorrect_delimiter.rs

Addresses issue: #8 
I had to change the `checkout` function in src/check.rs - In order for different types to be bundled into a `Vec`, it needs to be wrapped in a `Box` which implements the `Check` trait.

Add check: Incorrect delimiter

---

CHANGELOG.md
src/lib.rs

For this I ignore inline comments, this can be implemented at a later stage.
closes #36

Add skipping of commented or empty lines

---

CHANGELOG.md
README.md
src/lib.rs
src/main.rs

Added cli argument --path or -p where you specify the path of the directory where you want dotenv-linter to run.
If there is no argument -p, the program use the current directory.

Add support for specified directory

---

src/checks.rs
src/common.rs
src/lib.rs

This PR fixes some issues:
* Extend the `.env` pattern to include the `*.env` files to check;
* Replace back `HashSet` to `Vector` to keep files' order;
* Remove duplicate file name definition;
* Add test coverage for the `FileEntry` struct.

Extend the default include files pattern

---

CHANGELOG.md
README.md
src/checks.rs
src/checks/leading_character.rs
src/checks/leading_space.rs

I created this proof of concept to use a regular expression in the leading space checker.
However, as I'm not the maintainer I don't know if this is the way where this project wants to go.
If you would go for it we have two options I can currently see:
* rename the leading space checker to something it really reflects (leading character checker or something)
* Combine some other checkers which only act on one line also into a regex and one checker (for example, I think it would be very easy to combine the leading space, spaces around equal, and uppercase key checker, quick and dirty and not fully functional: `^[#A-Z_]*=.*`
closes #56

Make leading space detector more robust and aware of allowed chars 

---

src/checks/incorrect_delimiter.rs
src/checks/lowercase_key.rs

* Changed IncorrectDelimiterChecker and LowercaseKeyChecker to use Line.get_key method

Use Line.get_key in all checkers

---

src/lib.rs

Removes the unused args : `--include` and `--path`
Close #102

[#102] Remove unused args

---

CHANGELOG.md
CONTRIBUTING.md
src/checks.rs
src/checks/duplicated_keys.rs
src/checks/incorrect_delimiter.rs
src/checks/key_without_value.rs
src/checks/leading_character.rs
src/checks/lowercase_key.rs
src/checks/spaces_around_equal.rs
src/checks/unordered_keys.rs

This change addresses a `TODO` comment from `checks.rs` which has to do with the way that lines are currently passed to the checkers.
Currently, the line is always cloned when the run method is executed but this might not be necessary in the cases where we do not generate a warning.
In order to only generate clones of the line entries when we actually need them, I have changed the parameter of the `run` method for the checkers to `&LineEntry`.

Use reference for the LineEntry as part of the run method for checks

---

CHANGELOG.md
src/checks/duplicated_keys.rs

The current `DuplicateKeyChecker` implementation uses a `Vec<String>` to store previously seen keys. This leads to an `O(n)` time-complexity when we check if a key is already present in the keys collection.
In order to improve the time-complexity of this checker, we can use a `HashSet<String>` which has `O(1)` time-complexity (on average) for the `contains` operation.

Use HashSet for DuplicateKeyChecker

---

CHANGELOG.md
src/lib.rs

closes #103 
current_dir.to_str is replaced with as_os_str which yields the OsString.
The argument type of get_args() function is changed from &str to &OsStr.
The clap code to get the argument `input` was using default_value method
which was converting OsString to &str. Instead default_value method is
swapped with default_value_os which accepts &OsString

Fix #103: Remove the unwrap method while working with the current directory

---

CHANGELOG.md
Cargo.toml

Change `release` profile defaults with values from [min-sized-rust](https://github.com/johnthagen/min-sized-rust)
Changes of binary size:
default values: 3.3M
optimized releaseprofile: 1.4M
Resolve #129

[#129] Minimizing Rust Binary Size

---

CHANGELOG.md
src/checks/unordered_keys.rs
tests/cli_test.rs

This PR fixes #126 added the check name `UnorderedKey` to the message and fixed the required tests to show this message as well.

UnorderedKey: Added check name in message and tests

---

.github/workflows/release.yml

I prepared a bit.
TODO:
closes #116

Release: Add workflow for AUR publishing

---

.github/workflows/ci.yml
CHANGELOG.md

What is cached:
* Cargo registry (the `.cargo/registry` directory), a cache key includes the `Cargo.lock` file's hash.
* Build files except the `dotenv-linter` package itself (the `target` directory), a cache key includes the `Cargo.lock` file's hash and the Rustc version hash.
* Grcov executable, a cache key includes the Grcov's version.
When cache hits, duration of CI workflow is about 50-60 seconds (vs 3.5-4 minutes without cache).
Also I have added the `minimal` profile in `actions-rs/toolchain` but the action continues to install additional tools (it may be related to [this issue](https://github.com/actions-rs/toolchain/issues/72)).
Possible improvements:
* Cache toolchain's files (about 15-20 seconds), but it may be kind of tricky to compose and expire a cache key.

Use actions/cache

---

.github/workflows/ci.yml

It seems that Rust team [removes](https://github.com/rust-lang/rust/pull/70175) a `no-landing-pads` compiler option yesterday.
And now there is an error in "Tests and coverage" job in CI workflow: "unknown debugging option: `no-landing-pads`".
I have fix it, but I am not sure of the correctness of this solution.

No landing pads fix

---

CHANGELOG.md
README.md
src/checks.rs
src/checks/extra_blank_line.rs
src/checks/key_without_value.rs
src/checks/leading_character.rs
src/lib.rs
tests/ending_blank_line.rs
tests/extra_blank_line.rs

@mgrachev, I still have to check `\n` when adding the last line entry (we discussed this earlier) because of the special case with extra blank line at the end of file.
Any ideas?

ExtraBlankLine checker

---

CHANGELOG.md
src/checks/incorrect_delimiter.rs

Fix for #187:
Replaced `&'static str` with `&'a str` for `IncorrectDelimiterChecker`.

IncorrectDelimiterChecker: Replace &'static str with &'a str (#187)

---

CHANGELOG.md
src/checks/ending_blank_line.rs

Changes the lifetimes from 'static to 'a in EndingBlankLineChecker
Fixes #185

Updated lifetimes in EndingBlankLineChecker

---

CHANGELOG.md
src/checks/leading_character.rs

Changes the lifetimes from 'static to 'a in LeadingCharacterChecker.
Fixes #188

Updated lifetimes in LeadingCharacterChecker

---

CHANGELOG.md
README.md
src/checks.rs
src/lib.rs

Added functionality that displays a list of all checks if there is an argument --show-checks for #199
This argument is terminal and terminates the dotenv-linter after displaying a list of available check names.
The test was added for a new function, it may also make sense in the CLI test, but in this case, we will need to manually add names to the test in case of publication of new checks.
A usage example has been added to README.

Add an argument to show available checks (#199)

---

CHANGELOG.md
src/checks/extra_blank_line.rs

I found the small bug in the `ExtraBlankLine` check: it prints less warnings than expected when there are several successive blank lines.
For example, it prints only one warning for this file (instead of two):
```env
A=B
B=C
```

Fix for the case when many extra lines

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/fs_utils.rs
src/lib.rs
tests/cli_common/mod.rs
tests/cli_specific.rs

To solve the [problem with the UNC prefix](https://github.com/dotenv-linter/dotenv-linter/issues/212#issuecomment-642741675) on Win, I added [dunce](https://crates.io/crates/dunce) deps (it is very lightweight).
This elegantly solves our problem at the moment :+1: 
<details>
<summary> Windows output </summary>
```
PS D:\workdir\dotenv-linter-win-x64> ./dotenv-linter ../test
..\test\incorrect.env:1 LeadingCharacter: Invalid leading character detected
..\test\incorrect.env:2 KeyWithoutValue: The RAILS_ENV key should be with a value or have an equal sign
..\test\incorrect.env:3 IncorrectDelimiter: The DB-NAME key has incorrect delimiter
..\test\incorrect.env:3 UnorderedKey: The DB-NAME key should go before the LOGGER_LEVEL key
..\test\incorrect.env:4 LowercaseKey: The DEbUG_hTTP key should …
```

Windows support path canonicalize

---

CHANGELOG.md
README.md
src/checks/unordered_key.rs
src/common.rs

In some projects, I work with large `.env` files which have more than 200 lines.
Sorting these files is a really big problem.
The solution is to use groups of lines separated by blank lines. For example:
```env
❌ Wrong
FOO=BAR
BAR=FOO
✅ Correct
BAR=FOO
FOO=BAR
✅ Correct
FOO=BAR
BAR=FOO
```

Consider blank lines in UnorderedKey check

---

CHANGELOG.md
src/checks.rs
src/lib.rs
src/main.rs

Move show-checks flag to main.rs

---

CHANGELOG.md
src/common.rs

in favor of `fs::read_to_string`
closes #232

Remove `FileEntry::get_content_by_path`

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
docs/install.md
install.sh

Implemented a script for more short way to install dotenv-linter (#112).
The advantage of the solution is its cross-platform.
The script is executed with `curl`/`wget` and even _under Windows_ (checked on `MINGW`).
Complexity is the process of automatically declaring an environment variable. In some cases, this is only possible manually at the moment.
This is a working version, I also tested on Alpine Linux.
**But I would like to hear any ideas for improving or changing the approach.**
Perhaps when we come to a final decision, it makes sense to create a separate repository.
Although for installing binaries with a script, it looks suitable in this repo, so far it is not more than 1 file.

Provide more short way to install dotenv-linter

---

CHANGELOG.md
src/checks.rs
src/checks/duplicated_key.rs
src/checks/ending_blank_line.rs
src/checks/extra_blank_line.rs
src/checks/incorrect_delimiter.rs
src/checks/key_without_value.rs
src/checks/leading_character.rs
src/checks/lowercase_key.rs
src/checks/quote_character.rs
src/checks/space_character.rs
src/checks/trailing_whitespace.rs
src/checks/unordered_key.rs
src/common.rs

I added the field with a checker name to `Warning` (it is possible to determine the checker by the text of the message, but I don't like this approach).
It is needed for the [Autofix](https://github.com/dotenv-linter/dotenv-linter/pull/228) feature.

Add check_name to Warning

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
docs/checks/unordered_key.md
docs/install.md

Just preparing for the release [v2.1.0](https://github.com/dotenv-linter/dotenv-linter/issues/217).
We also need to update the relevance: [homebrew-tap](https://github.com/dotenv-linter/homebrew-tap) and [action-dotenv-linter](https://github.com/dotenv-linter/action-dotenv-linter)

Release v2.1.0

---

CHANGELOG.md
README.md
docs/quick_start.md
src/lib.rs
src/main.rs
tests/args/current_dir.rs
tests/args/specific_path.rs
tests/checks/ending_blank_line.rs
tests/checks/extra_blank_line.rs
tests/cli.rs
tests/flags/mod.rs
tests/flags/quiet.rs
tests/flags/recursive.rs
tests/options/exclude.rs
tests/options/mod.rs

This PR originates from #240.  
I decided to add an additional flag to be able not to display verbose information such as "Found n problems".
In #240 PR uses the flag `--no-color` for this, but I think we should add the additional flag `--quiet`.

Add total problems to output and --quiet argument

---

CHANGELOG.md
src/fixes.rs
src/fixes/key_without_value.rs
tests/fixes/mod.rs

fixes https://github.com/dotenv-linter/dotenv-linter/issues/247

Add key without value fixer

---

CHANGELOG.md
src/fixes.rs
src/fixes/trailing_whitespace.rs
tests/fixes/mod.rs
tests/fixes/trailing_whitespace.rs

Add `TrailingWhitespaceFixer` and included it in the `fixlist`.
Update `unfixed_warnings` and `multiple_files` tests to reflect the new
fix and to use `ExtraBlankLine` as an unfixed warning example.

Add trailing whitespace fix

---

.github/workflows/ci.yml
CHANGELOG.md

Closes https://github.com/dotenv-linter/dotenv-linter/issues/231
Updated to use the new cache version:
1. Use multiple cargo paths in the same block
2. Cache the grcov binary

Actions uses cache@v2

---

CHANGELOG.md
src/main.rs

1. Small refactor to bucket the warnings vector into fixed/unfixed using a `partition` closure.
In my opinion, this seems clearer to read and more idiomatic than running two separate filter iterations.

Partition fixed/unfixed warnings

---

CHANGELOG.md
README.md
docs/checks/unordered_key.md
src/checks.rs
src/checks/unordered_key.rs
src/common/line_entry.rs

I changed the `UnorderedKey` check's logic.
Now it also splits lines into sortable groups by control comments.
This is done to make the linter logic more predictable.
File:
```
BB=1
Aa=B
X=X
```
There is one warning (line 3).
After fixing we expect something like this:
```
Aa=B
BB=1
X=X
```
And we will get the incorrect file after fixing.
If we fix the `Aa` key somehow, it will not be the best solution either, because a user obviously doesn't want fix the lower case.
File:
```
BB=1
Aa=B
X=X
```
There is no warnings.

Group lines by control comments

---

CHANGELOG.md
src/checks.rs
src/checks/unordered_key.rs

I have found a bug in this PR https://github.com/dotenv-linter/dotenv-linter/pull/281.
If we run `dotenv-linter` against this file:
```env
BB=1
Aa=B
X=X
```
We will get the warning:
```bash
$ dotenv-linter .env
.env:3 UnorderedKey: The Aa key should go before the BB key
```
@evgeniy-r Please take a look at it 👀

Fix a bug with UnorderedKeyChecker and control comments

---

CHANGELOG.md
tests/checks/ending_blank_line.rs
tests/checks/extra_blank_line.rs
tests/common/mod.rs
tests/common/output.rs

This PR adds a `check_output` function for integration tests, and refactors current tests to use it. The added function is made to be similar to `fix_output`, which already exists.
Resolves: #293
~- [ ] This PR has been added to [CHANGELOG.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CHANGELOG.md) (at the top of the list);~
~- [ ] Tests for the changes have been added (for bug fixes / features);~
~- [ ] Docs have been added / updated (for bug fixes / features).~
Crossed out the above since this is just an internal improvement. Let me know if there's anything else I should do!

Add check_output function for integration tests

---

.github/workflows/shellcheck.yml
CHANGELOG.md

This PR removes the ununsed environment variable **$CARGO_TERM_COLOR** in the shellcheck GitHub workflow.

Remove unused variable `CARGO_TERM_COLOR` in shellcheck workflow

---

CHANGELOG.md
Dockerfile

```rust
error[E0658]: use of unstable library feature 'str_strip': newly added
--> src/common/comment.rs:17:10
|
17 |         .strip_prefix(format!("{}:", PREFIX).as_str())?
|          ^^^^^^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/67302
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: could not compile `dotenv-linter`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dotenv-linter v2.2.0 (/usr/src/dotenv-linter)`, intermediate artifacts can be found at `/usr/src/dotenv-linter/target`
```

Fix docker release

---

.github/workflows/ci.yml
CHANGELOG.md

Fixes #318.
Removed the `set-env` action ([soon deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)). Used instead [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).

feat(GH-318): change soon deprecated set-env action

---

CHANGELOG.md
src/common/file_entry.rs

First stab at #323
This implementation hard-excludes files and there is no way to run checks on them.
Even running the linter with these files listed explicitly will still skip them.

Add default exclude list

---

CHANGELOG.md
src/lib.rs
tests/common/mod.rs
tests/common/test_dir.rs
tests/common/test_link.rs
tests/flags/recursive.rs

When in recursive mode: do not follow symbolic links within target directories. See #326.
- Add check in crate::get_file_paths to only get subdirectories if
they are not symlinks.
- Add test with a cyclic symlink.
- Add symlink creation function for unix and windows to use in test.

Fix cyclic symbolic link recursion

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/common/output/check.rs
src/common/output/fix.rs
src/lib.rs
src/main.rs
tests/common/test_dir.rs
tests/flags/backup.rs
tests/flags/quiet.rs
tests/output/fix.rs

Remade flags to subcommands

---

CHANGELOG.md
src/common.rs
src/common/compare.rs
src/common/output/compare.rs
src/common/output/mod.rs
src/lib.rs
src/main.rs
tests/cli.rs
tests/compare/compare.rs
tests/compare/mod.rs

A proof of concept how comparing could work.
I think this isn't the cleanest implementation and needs some abstraction work in terms of types, and duplicate work between `compare` and `run` but I wanted to see if it can work and how it could work.
We didn't already agreed that this feature needed to be added to the tool, but I liked the idea, found some time and had fun playing around with it.
So this could be the starting point of a discussion and further investigation of that topic.
What do you think?
Check this feature:
```sh
echo HELLO=value >> .env
echo HELLO=value >> .env.local
echo WORLD=value >> .env
dotenv-linter --compare .env .env.local
cargo run -- --compare .env .env.local
```

Add compare command

---

CHANGELOG.md
src/common/file_entry.rs
src/fs_utils.rs
tests/flags/backup.rs

also:
* add `.bak` extension to backup files
What are your thoughts on this solution @dotenv-linter/core - is this the right way to do it?
closes #359

feat: dont lint backup files

---

CHANGELOG.md
src/lib.rs

This is a pretty simple solution, but I would not like to see the `CI failing` status for a long time 🙂 
Closes #373

fix: remove extra Result wrapping to fix clippy

---

.github/workflows/ci.yml
CHANGELOG.md

The [clippy-check](https://github.com/actions-rs/clippy-check) action allows to execute `clippy` and posts all warnings as annotations to PR's.
I think it's very useful to see all the warnings on the `Files changed` tab, instead of looking for them in the logs.
Example:

ci: use clippy check action

---

CHANGELOG.md
src/common.rs
src/common/line_entry.rs
src/fixes/ending_blank_line.rs
src/lib.rs

Use Rc for LineEntry to reduce memory consumption

---

CHANGELOG.md
src/common/output/check.rs
src/lib.rs
tests/options/exclude.rs
tests/output/check.rs

This implements #384 
I had to change the exclude tests as well, as they just excluded all loaded files... :)

Print message if there are no input files (#384)

---

CHANGELOG.md
src/common/line_entry.rs

Implements https://github.com/dotenv-linter/dotenv-linter/issues/379.
I decided to change the return type of the method to:
```rust
pub fn get_substitution_key(&self) -> Result<Vec<&str>, &'static str>
```
because of cases like `FOO=$BAR$BAZ` -> `["BAR", "BAZ"]`
and because there could be an errors while parsing keys.
UPD: final function signature is:
```rust
pub fn get_substitution_key(&self) -> Vec<&str>
```
Function should stop parsing on error and return parsed keys: `FOO=$BAR ${BAZ $BAM` -> `["BAR"]`

Add method to get substitution keys to LineEntry (#379)

---

CHANGELOG.md
src/common.rs
src/common/line_entry.rs
src/fixes/ending_blank_line.rs

Closes https://github.com/dotenv-linter/dotenv-linter/issues/403.

Get rid of String::from when creating LineEntry

---

CHANGELOG.md
src/checks/unordered_key.rs

Solves [#382](https://github.com/dotenv-linter/dotenv-linter/issues/382)

Allow unordered keys for substitution variables (#382)

---

CHANGELOG.md
src/common/output/fix.rs
src/lib.rs

Regards (#409). 
Are there any cases where this issue occurs?  If so, I could add a test case.

Check if the amount of predicted checks match the amount of checks done, print warning if not.

---

CHANGELOG.md
src/checks/quote_character.rs

Added condition to return None if the value of the variable contains $ character

addressing issue #408

---

CHANGELOG.md
src/checks.rs
src/checks/duplicated_key.rs
src/checks/ending_blank_line.rs
src/checks/extra_blank_line.rs
src/checks/incorrect_delimiter.rs
src/checks/key_without_value.rs
src/checks/leading_character.rs
src/checks/lowercase_key.rs
src/checks/quote_character.rs
src/checks/space_character.rs
src/checks/substitution_key.rs
src/checks/trailing_whitespace.rs
src/checks/unordered_key.rs
src/common.rs
src/common/warning.rs

Refactors the unit tests for Check implementations as per #419. 
Unit tests have been replaced with a new check_tester macro which takes care of the boiler plate of writing multiple test cases. This would make the tests easier to change when an interface change is required, such as #410, as only the expanded code of the macro is changed to reflect the new API.  
This change would also effect #414 and once that PR is merged I'm happy to make the changes so that it is included in this refactoring :)
Closes #419

Refactor Check unit tests

---

.github/workflows/release.yml
CHANGELOG.md
install.sh

`aarch64` support for mac, linux, windows
These might be useful changes because aarch64 is gaining popularity.
Closes #435

build: add aarch64 support

---

CHANGELOG.md
src/fs_utils.rs
src/lib.rs
src/main.rs

A little refactoring of the code.
Moved a repetitive `Box <dyn Error>` into a separate `Result` type.

Add type alias for `Result`

---

CHANGELOG.md
src/checks/ending_blank_line.rs
src/common.rs
src/common/line_entry.rs
src/fixes/ending_blank_line.rs
src/lib.rs

Get rid of `Rc<FileEntry>` in `LineEntry`

---

.gitignore
CHANGELOG.md
src/checks.rs
src/checks/substitution_key.rs
src/common.rs
src/common/line_entry.rs
src/fixes.rs
src/fixes/substitution_key.rs
src/fixes/unordered_key.rs
src/lib.rs
tests/fixes/fixtures/complicated.env
tests/fixes/fixtures/complicated.env.golden
tests/fixes/fixtures/correct.env
tests/fixes/fixtures/correct.env.golden
tests/output/check.rs

Proof of concept for real multi-line value support #442.
~~It's temporary ugly solution, but it works.~~
Currently, I have added support of real multiline single-quoted values.
This implementation allows us to perform all checks on such values, since they are transformed into one `LineEntry`.
@dotenv-linter/core  I suggest to consider this PR and, if approved, add support of multiline  double-quoted values in another pull request (if needed at all) 🤔 
Partially closes #442

feat: add support for multi-line single-quoted values

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli.rs
src/common/quote_type.rs
src/lib.rs
tests/args/current_dir.rs
tests/args/specific_path.rs
tests/checks/duplicated_key.rs
tests/checks/ending_blank_line.rs
tests/checks/extra_blank_line.rs
tests/checks/incorrect_delimiter.rs
tests/checks/key_without_value.rs
tests/checks/leading_character.rs
tests/checks/lowercase_key.rs
tests/checks/quote_character.rs
tests/checks/space_character.rs
tests/checks/substitution_key.rs
tests/checks/trailing_whitespace.rs
tests/checks/unordered_key.rs
tests/common/args.rs
tests/common/mod.rs
tests/common/test_dir.rs
tests/fixes/mod.rs
tests/flags/check_updates.rs
tests/flags/mod.rs
tests/flags/quiet.rs
tests/flags/recursive.rs
tests/options/exclude.rs
tests/output/check.rs

Add check for new version

---

CHANGELOG.md
src/lib.rs

Hi everyone! I have substituted `Option<Values>` check and empty vector creation with `unwrap_or_default()`, because `Values` is an iterator, and it's default value is an empty iterator.

refactor: skip_checks with use default iterator

---

.github/workflows/ci.yml
CHANGELOG.md
benches/fix.rs

Hi everyone! I refactored typehints, lifetimes and `ArgMatches` generation in check bench, and added `--all-targets` flag in check ci.

refactor: check ci with all-targets arg

---

CHANGELOG.md
src/checks.rs
src/checks/value_without_quotes.rs
src/common/lint_kind.rs
src/fixes.rs
src/fixes/value_without_quotes.rs
tests/checks/mod.rs
tests/checks/value_without_quotes.rs
tests/fixes/mod.rs
tests/fixes/value_without_quotes.rs

When evaluating variables, values with spaces will only evaluate the first word/character before a space and ignore the rest. This is especially bad because this fails silently in most cases and can lead to confusing scenarios.
This ensures that any value that contains a space must have quotes surrounding it so that it is valid.
This does not consider any value that has a leading or trailing space since that is managed by other checks/fixes.
Further Fixes: https://github.com/dotenv-linter/dotenv-linter/issues/343

feat: Add check for values that require surrounding quotes

---

.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md

ci: add docker arm64 image

---

CONTRIBUTING.md

Suggestion proposed on #555 
> I'm thinking that maybe adding a hook to control this would be a great addition, let me know if you would like me to do it in this PR or another one

Add commit standar for the CONTRIBUTION file

---

src/checks/quote_character.rs

Ensure that values containing would-be comments are not altered by stripping quotes.
Refs: #559

fix: don't remove quotes for values containing hash-sign

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/release.yml
rust-toolchain.toml
src/common/comment.rs
src/common/line_entry.rs
src/common/warning.rs
src/lib.rs

Because `actions-rs` [is unmaintained](https://github.com/actions-rs/toolchain/issues/216).

ci: replace `actions-rs/toolchain` with `dtolnay/rust-toolchain`

---

benches/check.rs
benches/compare.rs
benches/fix.rs
src/checks.rs
src/cli/mod.rs
src/cli/options.rs
src/common/lint_kind.rs
src/lib.rs
tests/flags/check_updates.rs

It was moved to help:
```
Lightning-fast linter for .env files
Usage: dotenv-linter [OPTIONS] [input]... [COMMAND]
Commands:
compare  Compares if files have the same keys [aliases: c]
fix      Automatically fixes warnings [aliases: f]
Arguments:
[input]...  files or paths
Options:
-e, --exclude [<FILE_NAME>...]  Excludes files from check
-s, --skip [<CHECK_NAME>...]    Skips checks [possible values: DuplicatedKey, EndingBlankLine, ExtraBlankLine, IncorrectDelimiter, KeyWithoutValue, LeadingCharacter, LowercaseKey, QuoteCharacter, SpaceCharacter, SubstitutionKey, TrailingWhitespace, UnorderedKey, ValueWithoutQuotes]
-r, --recursive                 Recursively searches and checks .env files
--no-color                  Turns off the colored output
-q, --quiet                     Doesn't …
```

refactor(cli): get rid of `list` command

---

.github/workflows/release.yml

ci: get rid of `set-output`

---

dotenv-linter/src/common/output/compare.rs
dotenv-linter/src/lib.rs
dotenv-linter/tests/compare/compare.rs

This addresses Issue: https://github.com/dotenv-linter/dotenv-linter/issues/647 
When two files are compared and no difference is found, the program prints 
```
Comparing file1...
Comparing file2...
```
This then ends and goes back to the command line. My PR will change the functionality to show
```
Comparing file1...
Comparing file2...
No difference found
```
This will add some clarity on the compare command that no difference was found and no error caused the program to finish prematurely.

feat: add "No difference found" message on successful compare

---

dotenv-linter/src/cli.rs
dotenv-linter/src/cli/options.rs
dotenv-linter/src/common/output/fix.rs
dotenv-linter/src/lib.rs
dotenv-linter/tests/output/fix.rs

feat: add `--dry-run` option to fix subcommand

---

.github/workflows/ci.yml

The `install_specific_versions` with version 2.1.1, 2.0.0, 1.1.1 on macos fails because there's no release for macos aarch for those versions.

ci: exclude installing v1 and v2 on macos
